name: Publish Bottles and Merge PR
on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'Automerge')
    runs-on: macos-14
    permissions:
      actions: read
      pull-requests: write
      contents: write
      packages: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: false

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Configure Git User
        uses: Homebrew/actions/git-user-config@master
        with:
          username: github-actions[bot]

      - name: Pull and Publish Bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          brew pr-pull \
            --debug \
            --artifact-pattern 'bottles_*' \
            --tap="$GITHUB_REPOSITORY" \
            --workflows ci.yml \
            '${{ github.event.pull_request.number }}'

      - name: Push Commits to Main
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main
          directory: ${{ steps.set-up-homebrew.outputs.repository-path }}

      - name: Delete PR Branch if Not Fork
        if: github.event.pull_request.head.repo.fork == false
        working-directory: ${{ steps.set-up-homebrew.outputs.repository-path }}
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin "$BRANCH"
